language:
  python

python:
  - "3.5"

cache: 
  pip

install:
  - pip install -r requirements.txt

before_script:
- pip install coverage
- pip install coveralls

script:
  - python test_sorn.py
  - coverage run test_sorn.py 

after_success:
- coveralls
