language: python

jobs:
  include:
    - os: linux
      python: 3.5
      env: TOXENV=py35
    - os: linux
      python: 3.6
      env: TOXENV=py36
    - os: linux
      python: 3.7
      env: TOXENV=py37
    - os: linux
      python: 3.8
      env: TOXENV=py38
    - os: linux
      python: 3.9
      env: TOXENV=py39

    - os: osx
      language: generic
      env: TOXENV=py35
    - os: osx
      language: generic
      env: TOXENV=py36
    - os: osx
      language: generic
      env: TOXENV=py37
    - os: osx
      language: generic
      env: TOXENV=py38

cache: pip

install:
  - pip install -r requirements.txt

before_script:
  - python --version
  - pip install coverage
  - pip install coveralls
  - pip install codecov

script:
  - python test_sorn.py
  - coverage run test_sorn.py

after_success:
  - codecov
