language:
  python

python:
  - "3.5"

cache: 
  pip

install:
  - pip install -r requirements.txt

before_script:
- pip install coverage
- pip install coveralls

script:
  - python test_RunSorn.py --with-coverage 

after_success:
- coveralls
